[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 9600
upload_port = COM3
monitor_port = COM3
lib_deps =
    esphome/ESPAsyncWebServer-esphome @ ^3.1.0
    esphome/AsyncTCP-esphome @ ^2.1.1
board_build.filesystem = littlefs